# SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: sidecar-rbac
description: Sidecar RBAC objects

type: application

version: v1.0.3
appVersion: v1.0.3
