LANDSCAPER_VERSION: v1.0.4

# ingress controller
# renovate: datasource=helm depName=ingress-nginx registryUrl=artifacthub.io/packages/helm
INGRESS_NGINX_CHART_VERSION: 4.14.1
# renovate: datasource=github-releases depName=ingress-nginx
INGRESS_NGINX_IMAGE_VERSION: v1.13.3
