# SPDX-FileCopyrightText: 2021 "SAP SE or an SAP affiliate company and Gardener contributors"
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: landscaper-service
description: Helm chart for landscaper as a service

type: application
version: v1.0.3
appVersion: v1.0.3
